### ISSUE TITLE
ToDo: Website should build from open issues

### ISSUE THREAD

**Issue by seichris** [seichris/issues-to-website#18]
- [x] opening/editing/closing issue triggers script. gh action by https://github.com/mattduck/gh2md/
- [x] script saves all issues into `issues.md`
- [ ] create one file per issue (see https://github.com/mattduck/gh2md/issues/13)
- [ ] format for the `.md` files should be similar to the files in `/content`

```
---

slug: 10
title: This bug is critical
description: >-
    Oh my. Better work out this one.
date: 2020-11-22T19:14:56.000Z
category: bug
state: proposed
url: https://github.com/seichris/issues-to-website/issues/10

----

##issue body

issue body
```

**Comment by seichris** [comment]
Once the website builds from open issues, we want to allow
- devs to set a price per issue
- funders to fund an escrow contract
- a service that watches the contract, to notify devs and funders if funding reached the price, and the issue can be worked on. (See Trust Wallet bot https://github.com/trustwallet/assets/pull/4896)


See https://www.figma.com/file/HG3SMVhTwfLUeIU04UoXDg/better.kontext.app-bounty-user-feedback?node-id=2%3A40

**Comment by seichris** [comment]
Start by opening a `better feedback` repo
